### ISSUE TITLE
Can't find Dives Akuru on https://fonts.google.com/noto

### ISSUE THREAD

**Issue by sridatta1** [notofonts/dives-akuru#17]
I can't spot on https://fonts.google.com/noto search. 
Perhaps the latest fonts are not migrated or is it because of the open issues and the font is not stable yet?

**Comment by simoncozens** [comment]
Onboarding a font from the Noto GitHub repositories to the fonts.google site is quite a process (by design - there's QA and other things to be done before they make their way to the main site).

The onboarding team are currently working through a backlog of about 100 Noto updates from last year, as well as all the other commissioned and submitted non-Noto fonts that need to be added to or updated on fonts.google.com. Unfortunately this means that *new* Noto families end up at the back of that queue unless I bump their priority. I have a number of new families which need to be added, so I'm going to flag them for prioritisation when they're all ready. You can track the progress of the Dives Akuru font onboarding at https://github.com/google/fonts/pull/5390.

**Comment by sridatta1** [comment]
Thanks for the detailed note, understood.
